### ISSUE TITLE
Server& hbs

### ISSUE THREAD

**Issue by AsalaKM** [FACG5/Qattan-foundation#4]
**Login Page**
- [x] login section

**Home Page**
- [x] user data section
- [x] welcome section
- [x] ticket view section

**Header& Menu Bar**
- [x]  for employee:
home
new ticket
logout

- [x] for manager:
home
inventory
technical support
loans
reports
logout
 
**Add Ticket**
- [x] technical support section
- [x] loans sections

**Technical Support**
- [x] view all ticket

**Technical Support Details**
- [x] view ticket detail
- [x] add action for ticket

**Loans**
- [x] view all ticket

**Loans Details**
- [x] view ticket detail
- [x] add action for ticket

**Inventories**
- [x] view section
- [x] update form
- [x] add new inventory section

**Reports**
- [x] by status section
- [x] by type section
- [x] by period section
